# Generated by Django 2.2.13 on 2021-07-11 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210711_2006'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomizeSettings',
        ),
    ]
