# Generated by Django 3.2.6 on 2021-08-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, default='img/featured-pic-1.jpeg', null=True, upload_to='posts/%Y/%m/%d/'),
        ),
    ]
