# Generated by Django 2.2.13 on 2021-07-11 17:48

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogintroheading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_intro_heading', models.CharField(default='Quick intro to our site', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Set blog intro context heading',
            },
        ),
        migrations.CreateModel(
            name='Customblogname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogname', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Blog name',
            },
        ),
        migrations.CreateModel(
            name='OverViewtext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview_text', tinymce.models.HTMLField(default='Arena fitness gym is aimed towards building a fit community in all fields. Enjoy!!')),
            ],
            options={
                'verbose_name_plural': 'set blog overview text',
            },
        ),
        migrations.CreateModel(
            name='Site_intro_context',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_intro_context', tinymce.models.HTMLField(default='Welcome arena fitness gym where fitness is not an option')),
                ('subscribe_newslater_description', tinymce.models.HTMLField(default='Subscribe to our RSS feeds and newslater for quick updates')),
            ],
            options={
                'verbose_name_plural': 'Set intro context',
            },
        ),
        migrations.CreateModel(
            name='Site_random_context',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('random_content', tinymce.models.HTMLField(default='Random page content will appear here')),
            ],
            options={
                'verbose_name_plural': 'Set random content',
            },
        ),
        migrations.CreateModel(
            name='Subscribe_newslater_description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribe_newslater_description', tinymce.models.HTMLField(default='Subscribe to our RSS feeds and newslater for quick updates')),
            ],
            options={
                'verbose_name_plural': 'Subscribe Newslate description',
            },
        ),
    ]
