# Generated by Django 2.2.13 on 2021-07-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogSettings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site_intro_context',
            name='subscribe_newslater_description',
            field=models.TextField(default='Subscribe to our RSS feeds and newslater for quick updates', max_length=255),
        ),
        migrations.AlterField(
            model_name='site_random_context',
            name='random_content',
            field=models.TextField(default='Random page content will appear here', max_length=255),
        ),
        migrations.AlterField(
            model_name='subscribe_newslater_description',
            name='subscribe_newslater_description',
            field=models.TextField(default='Subscribe to our RSS feeds and newslater for quick updates', max_length=255),
        ),
    ]
