# Generated by Django 3.2.5 on 2021-07-12 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogSettings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ranks',
            options={'verbose_name_plural': 'Ranks'},
        ),
    ]
