# Generated by Django 2.2.13 on 2021-07-11 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogSettings', '0005_auto_20210711_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site_intro_context',
            name='subscribe_newslater_description',
        ),
    ]
