# Generated by Django 2.2.13 on 2021-07-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogSettings', '0006_remove_site_intro_context_subscribe_newslater_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site_intro_context',
            name='site_intro_context',
            field=models.TextField(default='Welcome arena fitness gym where fitness is not an option', max_length=255),
        ),
    ]
