# Generated by Django 2.2.13 on 2021-07-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogSettings', '0007_auto_20210711_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rank', models.CharField(default='Instructor', max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=12)),
            ],
            options={
                'verbose_name_plural': 'Set Contacts',
            },
        ),
        migrations.CreateModel(
            name='Helpdesk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='asiafric@gmail.com', max_length=100)),
                ('tel', models.CharField(default='254711349412', max_length=12)),
                ('facebook', models.URLField()),
                ('twitter', models.URLField()),
                ('youtube', models.URLField()),
                ('instagram', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Help desk setup',
            },
        ),
    ]
