# Generated by Django 2.2.13 on 2021-07-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogSettings', '0008_contacts_helpdesk'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpdesk',
            name='physical_location',
            field=models.CharField(default='Maseno student center - Wing A', max_length=255),
        ),
        migrations.AddField(
            model_name='helpdesk',
            name='street_address',
            field=models.TextField(default='Siriba campus - Nyawita', max_length=255),
        ),
    ]
