# Generated by Django 2.2.13 on 2021-07-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogSettings', '0009_auto_20210711_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpdesk',
            name='rights_year',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
