# Generated by Django 2.2.13 on 2021-07-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogSettings', '0010_helpdesk_rights_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpdesk',
            name='other',
            field=models.URLField(default='enter any aditional social media url'),
        ),
    ]
