# Generated by Django 3.2 on 2021-07-11 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogSettings', '0013_auto_20210711_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='dateadded',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
